name: Merge and Rename Files

on:
  push:
    branches:
      - main

jobs:
  merge-and-rename:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Merge changes from main to uat and rename files
      run: |
        git checkout main
        git pull origin main
        git checkout uat
        git pull origin uat
        git merge main --no-commit
        git mv dev_app.py uat_app.py
        git mv dev_main.py uat_main.py
        git add .
        git commit -m "Merge changes from main and rename files"
        git push origin uat
