name: Merge and Rename Files

on:
  push:
    branches:
      - uat
      - main

jobs:
  merge-and-rename:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Check if merge is from main to uat
      run: |
        if [ "${{ github.event_name }}" == "push" ] && [ "${{ github.ref }}" == "refs/heads/uat" ]; then
          merged_branch=$(git log -1 --pretty=format:%P)
          if echo "${merged_branch}" | grep -q "refs/heads/main"; then
            git checkout uat
            git mv dev_app.py uat_app.py
            git mv dev_main.py uat_main.py
            git commit -am "Renamed files from dev branch"
            git push origin uat
          fi
        fi
